server:
  port: 10000
spring:
  application:
    name: eureka-client-a
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10114/eureka