server:
  port: 20000
spring:
  application:
    name: user-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10114/eureka